# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("calculator.proto", :syntax => :proto3) do
    add_message "calculator.AddRequest" do
      optional :a, :int32, 1
      optional :b, :int32, 2
    end
    add_message "calculator.AddResponse" do
      optional :sum, :int32, 1
    end
  end
end

module Calculator
  AddRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calculator.AddRequest").msgclass
  AddResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calculator.AddResponse").msgclass
end
